### ISSUE TITLE
KCD - Australia 2023 (August 22)

### ISSUE THREAD

**Issue by bradmccoydev** [cncf/kubernetes-community-days#391] opened 2021-04-06 02:37 UTC
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* Event Location: Doltone House Hyde Park
* Event Date and Time: August 22, 2023
* Event type: In-Person
* Expected Number of Attendees: 400
* Tracks/Days: 1-day event

### Organizers
* Organizer 1: Brad McCoy, Basiq, bradmccoydev@gmail.com, CNCF Slack Username - Brad McCoy
* Organizer 2: Matthew Flannery, Accelera, CTO, flannery.matt@gmail.com, CNCF Slack Username - Matt Flannery
* Organizer 3: Sharlene Tee, Sysdig, sharlene.tee@sysdig.com, CNCF Slack Username - Sharlene Tee
* Organizer 4: Brendon Thwaites, Founder, Brendon@zeroq.net.au, CNCF Slack Username - Brendon Thwaites
* Organizer 5: BMK Lakshminarayanan, lbmkrishna@gmail.com, CNCF Slack Username - BMK Lakshminarayanan
* Organizer 6: Dionne, Solo.io, dionne.phay@solo.io, CNCF Slack Username - Dionne Phay

### Submission checklist:
Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Minimum of 3 sponsors committed (not required to be confirmed ahead of the KCD event)
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and payout expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP
* [x] Event date and time has been chosen
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a [LinkedIn Page](https://www.linkedin.com/company/kubernetes-community-days-australia/) or Twitter handle specific to your KCD event - @kcd_australia

CfP open and close dates:
Website launch date:

### Submission checklist for CNCF:
* [x] Organizer email alias has been created: [organizers-australia@kubernetescommunitydays.org](mailto:organizers-australia@kubernetescommunitydays.org)
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created

### Post Event checklist:
* [x] Removed from Bevy header
* [x] CFP deactivated

### Sponsors
* Sponsor 1: Sysdig
* Sponsor 2: Harness
* Sponsor 3: 
* Fiscal sponsor that will accept payments: Matt Flannery's

**Comment by xmulligan** [comment] 2021-04-06 15:23
Hi @bradmccoydev thanks for putting this together! I'm going to uncheck the 3 organizers and twitter boxes until the information has been filled in. Let me know if there is anything I can do to help and I'm really looking forward to seeing this come together :)

**Comment by matthewflannery** [comment] 2021-04-06 22:40
Hey Bill, thanks for mentioning this to me. @bradmccoydev I'm keen to help if you would like to have me.

**Comment by bradmccoydev** [comment] 2021-04-07 00:06
Hey @matthewflannery of course! I actually tried to ping you on the CNCF slack to ask you yesterday.  I have added you to the list of organizers. Let's catch up about this maybe at the end of our next SIG-Security meeting?

**Comment by xmulligan** [comment] 2021-04-07 09:43
Glad I could help make the connection. I've also reached out to Sarah Wright from Mechanical Rock because she previously expressed interest in a KCD Australia, but haven't heard back yet.

As you start going through the planning and getting more things sorted, please feel free to reach out if there is anything I can do to help. Also always happy to have a call with you if needed https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-04

**Comment by matthewflannery** [comment] 2021-06-02 01:52
Rather than Oct 21, we are now looking at Mar 22 to allow for planning of an in-person conference.

**Comment by bradmccoydev** [comment] 2021-07-20 02:19
@scotty-c and @jorgearteiro will be helping out also

**Comment by xmulligan** [comment] 2021-08-05 11:48
I would like to schedule a monthly check in with you until the event so we have a regular check in point where I can help you with any issues that have arisen. Obviously, you can also contact me or have a meeting outside that time too. Can you suggest a time that works for you?

**Comment by xmulligan** [comment] 2021-08-05 11:48
I would like to schedule a monthly check in with you until the event so we have a regular check in point where I can help you with any issues that have arisen. Obviously, you can also contact me or have a meeting outside that time too. Can you suggest a time that works for you?

**Comment by bradmccoydev** [comment] 2021-08-10 08:06
> I would like to schedule a monthly check in with you until the event so we have a regular check in point where I can help you with any issues that have arisen. Obviously, you can also contact me or have a meeting outside that time too. Can you suggest a time that works for you?

Hi @xmulligan sure, what timezone are you in atm?

**Comment by xmulligan** [comment] 2021-08-10 08:42
@bradmccoydev I'm currently in CEST (Germany)

**Comment by bradmccoydev** [comment] 2021-08-16 09:20
ok we are having our monthly meeting tomorrow, but unfortunately, it is at 4am CEST, I will add another meeting on your calendar later this week to catch up with @matthewflannery and myself

**Comment by xmulligan** [comment] 2021-08-16 10:05
@bradmccoydev yes, sadly won't make that one. If you can't find a time in my calendar, then suggest a few times and I can make something work

**Comment by xmulligan** [comment] 2021-08-25 10:34
@bradmccoydev just wanted to follow up on this. Can you book a meeting? https://calendly.com/billmulligan/1-1-with-bill-mulligan

**Comment by xmulligan** [comment] 2021-10-19 12:08
@bradmccoydev can you give me access?

**Comment by xmulligan** [comment] 2021-11-03 13:57
@bradmccoydev I was looking through and you should actually already have access to both. Check on community.cncf.io and https://kcd.smapply.io/

**Comment by xmulligan** [comment] 2021-11-23 12:15
Currently choosing between two venues and the first sponsors have been secured. Considering a date in July now.

**Comment by k8tgreenley** [comment] 2022-06-13 18:50
@bradmccoydev I know you have postponed your event, I wanted to check in to see if you have confirmed new dates?

**Comment by AudMonte01** [comment] 2022-08-29 23:21
Thank you @bradmccoydev, Wilhelm for meeting today! Here are the notes and to-dos from our meeting:

* New date: Early 2023 (possibly March)
* Flow of Show: 1-day / single track
* Venue: TBD
* Sponsors are lined up
* Re-opening CFP once dates are locked in

**Comment by alexgleith** [comment] 2022-10-12 03:46
Keen to find out about this event, commenting to stay updated :-)

**Comment by AudMonte01** [comment] 2022-12-06 01:40
Thank you @bradmccoydev for meeting with me today. Here are my notes from the meeting:

Sponsors
* Sysdig is going sponsor!
* Matt F's company will be the fiscal sponsor

Venue
* Is flexible in expanding but a little more expensive than Pier One (beautiful outdoor venue)

Time: Early April 2023
Attendees: 250 goal

Diversity is hard, but running some programs
* "Hippy Hacker" contracts with CNCF re mentoring program

**Comment by AudMonte01** [comment] 2022-12-13 14:56
12/12 PST / 12/13 AEST MEETING NOTES

Solo.io (vendor on top of Istio) - willing to help with creating the website
Doltone House is harder because of wedding season - so they are looking into July now

To-Do
* Audra to collect 2019 Kubernetes Forum Sydney turn out rate

**Comment by k8tgreenley** [comment] 2023-02-08 15:25
Here is your organizer email alias: organizers-australia@kubernetescommunitydays.org

**Comment by AudMonte01** [comment] 2023-05-02 00:06
May 1/2 MEETING NOTES

Ticket sales
* Open on May 31
* Audra shared KCD registration questions in organizer slack channel

Sponsors
* 4 sponsors confirmed
* 10 sponsors are interested

Insurance
* Other than liability insurance and cancellation clauses with the venue, @k8tgreenley - can you list other event-driven insurances the team should think on?

Venue space
* Pyrmont Theatre, International Convention Center Sydney (same location where AWS ran their summit)
* Can scale from 400-1000

To-Do
* Audra add link in drop-down
* Organizers to link sponsor prospectus on the Bevy page

**Comment by AudMonte01** [comment] 2023-05-23 02:53
May 22 MEETING UPDATES

* Sponsors: 6 committed and 1 paid
* CFP: 14 submitted and 23 in progress
* Tickets: Getting registration up by Monday
* Volunteers: Possibly through the sponsor ticket allotment and diversity scholarship

To-Do
* Audra to send exam and CNCF store voucher codes

**Comment by AudMonte01** [comment] 2023-06-27 22:02
JUNE 27 MEETING UPDATES

Agenda
* CFP closes this Friday
* Confirm speakers next week and announcing curated content
* Hold 5 slots for curated content
* Use the 4 CNCF Ambassadors on the program committee to get last-minute submissions and coach under-represented voices

Other marketing efforts
* Audra updated KubeWeekly newsletter to link to tickets instead of CFP
* Audra updated ticketing in Bevy to be external ticketing platform 

Slide templates for speakers
* Not required, but nice to have for those who don't have the graphic chops and need a starting point

**Comment by AudMonte01** [comment] 2023-08-15 00:13
AUGUST 14 MEETING NOTES

* Registrations are at 297 as of today
* Not recording the sessions
* Attendees will have use of an event app

Actions
* [ ] K8s adoption statistic. @bradmccoydev - do you have this, or want me to pull this data?
* [ ] Opt-ins for CNCF communications is about 40%. Team to add folks as KCD Australia chapter members and survey for event feedback

**Comment by bradmccoydev** [comment] 2023-08-29 00:06
This event has now been complete

**Closed** 2024-01-18 21:24 UTC
Labels: complete, APAC KCD
