### ISSUE TITLE
KCD Pakistan 2023 (February 17)

### ISSUE THREAD

**Issue by Saim-Safdar** [cncf/kubernetes-community-days#406] opened 2021-07-14 12:01 UTC
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Location:
Islamabad FAST University

### Event Date and Time:
February 20, 2023

### Event type: 
in-person event

### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Minimum of 3 sponsors committed
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP
* [x] Please list who should be added as an admin for the CFP:
* [x] Event date and time has been chosen
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used) 
* [x] Provided CNCF access to all event social handles

CfP open and close dates:
Website launch date:

### Submission checklist for CNCF:
* [x] Organizer email alias has been created
* [x] Region created in Bevy
* [ ] Added to Bevy header
* [x] CfP created

### Post Event checklist:
* [ ] Removed from Bevy header
* [ ] CfP deactivated
* [ ] Videos uploaded to Youtube and linked to event page

### Expected Number of Attendees:
300

### Organizers
Salman Iqbal, Learnk8s, MLOps & Kubernetes Instructor, salman@learnk8s.io, Slack: Salman Iqbal
Saim Safdar, Wanclouds, Developer Advocate, saimsafder14@gmail.com, Slack: Saim Safdar
Bart Farrel, DoKC Community Lead, CNCF Ambassador, bart@dok.community, Slack: Bart Farrel

### CFP Admin
Saim Safdar, Rafay Systems, Developer Relations Manager , saimsafder14@gmail.com, Slack: Saim Safdar
TBD 

### Sponsors
TBD 
We are looking for sponsorship, anyone who is interested can contact  organizers-pakistan@kubernetescommunitydays.org

### Fiscal sponsor that will accept payments
TBD

**Comment by xmulligan** [comment] 2021-07-23 10:56
@Saim-Safdar really glad to see this event moving forward! Do you think you will have enough time to run a CfP and review the applications if the event is only 7 weeks away?

We also just updated the template with two more things:

- [ ] all organizers needs to take https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/
- [ ] can you provide me access to the social handles for the events?

**Comment by xmulligan** [comment] 2021-07-23 10:59
I've also added all of you to the organizers-pakistan@kubernetescommunitydays.org email forward

**Comment by Saim-Safdar** [comment] 2021-07-24 11:15
> @xmulligan it's going to be held in November, Date is updated, 
> 
> We also just updated the template with two more things:
> 
> * [ ]  all organizers needs to take https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/
> * [x]  can you provide me access to the social handles for the events?
[Twitter Handle](https://twitter.com/KCDPaksitan)
[LinkedIn](https://www.linkedin.com/company/kubernetes-community-days-pakistan/)
Facebook TBD
Instagram TBD

**Comment by xmulligan** [comment] 2021-07-26 16:31
Thanks for the update on the date, I think it will give you more time to put on an awesome event!

Thanks for the links, but we would also like to have control of the social accounts so we can ensure continuity of events

Let me know when you all have taken the course and I can set up the Bevy and SM Apply

**Comment by xmulligan** [comment] 2021-08-05 11:47
I would also like to schedule a monthly check in with you until the event so we have a regular check in point where I can help you with any issues that have arisen. Obviously, you can also contact me or have a meeting outside that time too. Can you suggest a time that works for you?

**Comment by Saim-Safdar** [comment] 2021-08-16 12:59
> I would also like to schedule a monthly check-in with you until the event so we have a regular check-in point where I can help you with any issues that have arisen. Obviously, you can also contact me or have a meeting outside that time too. Can you suggest a time that works for you?

 04:00 - 05:00 PM PKT Any day, would like to join and share the progress of the event with you.

**Comment by xmulligan** [comment] 2021-08-16 13:04
@Saim-Safdar perfect, I just sent you the invite for next Wednesday. Looking forward to speaking then!

**Comment by Saim-Safdar** [comment] 2021-08-16 13:08
Awesome, I always enjoy the time spending with you.

**Comment by xmulligan** [comment] 2021-11-05 13:47
thinking about opening cfp on the 26th of november, closing on 26th of december. Event end of january. Working with local communities about a hybrid event. Thinking about teaching the basics in less than 10 talks. Meeting again on the 25th of November

**Comment by xmulligan** [comment] 2022-01-10 12:18
@Saim-Safdar I wanted to check back in with you after the holidays. Do you have any updates on the program?

**Comment by k8tgreenley** [comment] 2022-05-02 18:49
Hi @Saim-Safdar I hope all is well with you. I saw that your Bevy account is set for June 17 - 18 but your ticket github issues states July. I want to confirm the dates of your event.

Also, want to check in on CFP, do you need any support at this time?

**Comment by AudMonte01** [comment] 2022-10-03 23:10
Adding notes from email exchange here:
* Organizers have secured the location of Islamabad FAST university for an in-person event
* The event will now be held on November 25 and 26

**Comment by ayesha54** [comment] 2022-11-07 15:56
How would I be able to join in person? whats the cost of the ticket?

**Comment by AudMonte01** [comment] 2022-11-08 17:18
NOTES FROM TODAY'S MEETING

Postpone mid (February 17th)
* more open source tools will be launched
* good for the Pakistan culture
* 1 track, 4 to 5-hour day

To-Dos
* Need multiple organizers from different companies who are also from the region
* Confirm February 17 date with the University
* Build a sponsor prospectus. You can use 
* @Saim-Safdar - do you want to wait to change the dates in Bevy so we can notify the people registered for the event once the venue has confirmed? 

Local University as the venue, and need date approvals
* Saim has taught a DevOps course there, so the venue space is FREE
* Accommodate up to 1k people
* 500 target attendance
* University can help with volunteers
* Fridays are good for the university because there are less classes
* They host 10 events a year, so they are prepared with security, etc

12 proposals accepted around KNative, Linkerdy, and so on
* Goal is to focus content on K8s security

Sponsors
* GitLab and Armory said they will commit as sponsors

**Comment by AudMonte01** [comment] 2022-12-06 17:00
Sponsors
* 2 local sponsors already in place
New Organizers
* Saim to send Audra names and email addresses of program committee who need access to SM Apply reviewing
Venue: NUST University (4-hour day)
* 1 keynote room, + small rooms (4 maintainer track)
* 500 attendees
* 12-14 sessions
* 25-minute sessions online offered
* Talks mostly in French
Registration
* Free
Website
* Branding and logo
CFP
* Open this week and close second week in January
To-Dos
* Audra to create Slack channel

**Closed** 2023-04-19 21:26 UTC
Labels: question, newevent

**Comment by AudMonte01** [comment] 2023-04-19 21:28
CNCF video playlist can be found here: https://youtube.com/playlist?list=PLj6h78yzYM2N2kRy5zsidZfpAKn2sGE3u
