### ISSUE TITLE
KCD China 2021

### ISSUE THREAD

**Issue by FeynmanZhou** [cncf/kubernetes-community-days#399] opened 2021-05-11 15:29 UTC
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Minimum of 3 sponsors committed
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP
* [x] Please list who should be added as an admin for the CFP: pengfeizhou@yunify.com
* [x] Event date and time has been chosen
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used) 
* [x] Organizer email alias has been created

CfP open and close dates:
Website launch date:

### Submission checklist for CNCF:
* [x] Organizer email alias has been created
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CfP created

### Post Event checklist:
* [x] Removed from Bevy header
* [x] CfP deactivated
* [x] Videos uploaded to Youtube and linked to event page

### Sponsor 1
Microsoft
### Sponsor 2
DaoCloud
### Sponsor 3
Nginx

### Fiscal sponsor that will accept payments

TBD

**Comment by xmulligan** [comment] 2021-05-18 15:19
@FeynmanZhou sorry for the delay on getting to this. I was out on vacation last week. 

It looks like you already have a lot of the boxes checked off! 

Since this will be in person, I have a couple of questions:
1. Do you know the exact date you want in August?
2. Do you have a location or event venue chosen?
3. Will this be a free event?
4. Who will the financial sponsor be?

Looking forward to working with you on this!

**Comment by FeynmanZhou** [comment] 2021-05-19 04:33
1. Do you know the exact date you want in August?
Will ensure the date soon.
2. Do you have a location or event venue chosen?
Beijing.
3. Will this be a free event?
Yes.
4. Who will the financial sponsor be?
Huawei, PingCAP, QingCloud

**Comment by xmulligan** [comment] 2021-05-20 16:55
Just an FYI. There will also be a KubeCon + CloudNativeCon China in early december https://www.lfasiallc.com/kubecon-cloudnativecon-open-source-summit-china/

as for 4, I meant "Fiscal sponsor that will accept payments" rather than the sponsors themselves :)

**Comment by xmulligan** [comment] 2021-06-03 09:19
@FeynmanZhou have you picked a date for the event yet? The middle of August is about 10 weeks away. Is there anything else you need from CNCF?

**Comment by FeynmanZhou** [comment] 2021-06-04 14:05
> @FeynmanZhou have you picked a date for the event yet? The middle of August is about 10 weeks away. Is there anything else you need from CNCF?

Due to the cronavirus, we plan to postbone the KCD China to the end of August or September.

**Comment by xmulligan** [comment] 2021-06-10 13:30
Great! Once you have the date chosen, let me know and I can create the region in Bevy. Is there anything else you need from me right now?

**Comment by xmulligan** [comment] 2021-06-24 23:06
@FeynmanZhou I just wanted to check back in with you. Have you chosen a date?

**Comment by xmulligan** [comment] 2021-07-23 11:01
@FeynmanZhou are you still planning on holding this event, is it delayed, or has it been canceled?

**Comment by FeynmanZhou** [comment] 2021-07-24 04:02
> @FeynmanZhou are you still planning on holding this event, is it delayed, or has it been canceled?

@xmulligan 

Sorry for the late reply.

After we discussed with the committee of KCD China, we plan to delay this event until the middle of October.

**Comment by xmulligan** [comment] 2021-07-28 15:53
@FeynmanZhou sure that also works. I've just given you access to SM Apply so you can set up the CfP

Once you choose an exact date, I can set up your account in Bevy

As a recent requirement, all organizers need to take https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/. Can you let me know when everyone has completed it?

**Comment by xmulligan** [comment] 2021-08-02 14:24
@FeynmanZhou Can you let me know when you plan on opening and closing the CfP and launching the event site?

**Comment by FeynmanZhou** [comment] 2021-08-03 16:38
> @FeynmanZhou Can you let me know when you plan on opening and closing the CfP and launching the event site?

Thanks @xmulligan !

I have received the account invitation from Bevy. I will inform all organizers to take the LF inclusive training and reply to you about the training, CFP plan, and event site this week.

**Comment by xmulligan** [comment] 2021-08-05 11:48
I would also like to schedule a monthly check in with you until the event so we have a regular check in point where I can help you with any issues that have arisen. Obviously, you can also contact me or have a meeting outside that time too. Can you suggest a time that works for you?

**Comment by FeynmanZhou** [comment] 2021-08-09 16:51
> I would also like to schedule a monthly check in with you until the event so we have a regular check in point where I can help you with any issues that have arisen. Obviously, you can also contact me or have a meeting outside that time too. Can you suggest a time that works for you?

@xmulligan  PST 5:00 pm to 9:00 pm is okay for us. I think we can schedule the first meeting to sync some updates for both this month.

**Comment by xmulligan** [comment] 2021-08-09 16:54
@FeynmanZhou I'm actually based in CEST (Germany). Do any times afternoon (China) work for you?

**Comment by xmulligan** [comment] 2021-08-16 12:59
@FeynmanZhou just wanted to follow up on this conversation. Do you have dates for the CfP, site, and event date? Also can you schedule a monthly check in with me? calendly.com/billmulligan/1-1-with-bill-mulligan

**Comment by xmulligan** [comment] 2021-09-10 14:39
Cfp launched on Monday through wechat
microsoft venue sponsor for both days
3 potential sponsors for gold
will run live stream with segmentfault and infoq

todo:
update website
take the training course

**Comment by FeynmanZhou** [comment] 2021-09-10 14:43
> Cfp launched on Monday through wechat
> microsoft venue sponsor for both days
> 3 potential sponsors for gold
> will run live stream with segmentfault and infoq
> 
> todo:
> update website
> take the training course

Thanks @xmulligan . This is the [meeting notes](https://docs.google.com/document/d/1VB__5EwhRYfkPGtcDgUwp1Z0oE9C1DVSWCZTIMywR30/edit#) of the KCD China weekly meeting.

### Done:

1. CFP program was officially announced on Monday via CNCF Subscription.
2. Introduce the sponsorship prospectus of KCD China 2021.
3. Microsoft has become the venue sponsor for KCD in Beijing and Shanghai.
4. Build partnership with two major technical media in China (Segmentfault and InfoQ).
5. Three organizations are interested in joining the gold sponsorship (F5, DaoCloud, Tencent Cloud), we need more negotiation.

### To do 

1. Update the official website of KCD China 2021.
2. Take the [training courses](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/.) with all organizers.
3. Confirm the gold sponsors with four organizations.

**Comment by xmulligan** [comment] 2021-09-23 14:47
Sponsors are confirmed and there are 24 CfP submissions.

Agenda and registration will be launched next week. Training course for organizers should also be finished then.

**Comment by FeynmanZhou** [comment] 2021-09-23 14:51
> Sponsors are confirmed and there are 24 CfP submissions.
> 
> Agenda and registration will be launched next week. Training course for organizers should also be finished then.

Thanks Bill, let add our meeting minutes today:

**2021-09-23 (Bi-weekly meeting with Bill)**

### Done:

1. The CFP program was closed on Sep 21. Received 24 proposals from 20 companies.
2. A new organizer from DaoCloud joined KCD China committee
3. All of the sponsors have been confirmed: 1 venue sponsor (Microsoft) and 2 gold sponsors, they will support two events (F5 and DaoCloud)
4. Contact the video livestream and photography for the physical event.

### To do:

1. Invite all CNCF ambassadors from China to vote for the gathered proposals.
2. Take the training courses with all organizers https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/.
3. Confirm the agenda and design a campaign poster
4. Launch the RSVP on CNCF WeChat Subscription, update the [KCD China site](https://community.cncf.io/kcd-china/).

**Comment by FeynmanZhou** [comment] 2021-10-10 11:05
2021-10-09 (Bi-weekly meeting with Bill)

### Done:

1. Invited all CNCF ambassadors from China to vote for the gathered proposals.
2. Confirmed the agenda and design a campaign poster
3. Launched the [RSVP]( https://community.cncf.io/kcd-china/) on CNCF WeChat Subscription, updated the [KCD China site](https://community.cncf.io/kcd-china/).

### To do:

1. Promote KCD China via CNCF WeChat Subscription and RSVP.
2. Take the training courses with all organizers https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/.
3. Confirm the venue and Livestream physically.
4. Preparing for tea break
5. Preparing for KCD promotional materials and poster

**Comment by FeynmanZhou** [comment] 2021-10-11 03:42
@xmulligan Could you please help to add two members (roby.chen@daocloud.io and yuki.dan@pingcap.com) to the organizers of KCD China? I didn't find their accounts in the system, but they have already registered.

![image](https://user-images.githubusercontent.com/40452856/136729871-9d1aa6dd-230c-47bb-aff1-9f6bfaa5b542.png)

**Comment by xmulligan** [comment] 2021-11-23 12:09
Awesome first in person KCD events! Congrats to @FeynmanZhou and the whole KCD China team. I can't wait to work with you in the future.

**Closed by xmulligan** 2021-11-23 12:09 UTC
Labels: newevent

**Comment by xmulligan** [comment] 2021-11-23 12:14
@FeynmanZhou do you have the totals for the number of CfP submissions and attendees for the Shanghai event?

**Comment by FeynmanZhou** [comment] 2021-11-23 16:20
> @FeynmanZhou do you have the totals for the number of CfP submissions and attendees for the Shanghai event?

@xmulligan 
Yes, I have, let me share these statistics with you via email. BTW, I am writing a wrap-up for the first-ever KCD China (Beijing and Shanghai), it could be completed this week. I hope you could help us to publish it at cncf.io.

**Comment by xmulligan** [comment] 2021-11-24 11:10
@FeynmanZhou Awesome! I would love to help you publish it on cncf.io too. Just send it when it is ready
