### ISSUE TITLE
KCD Istanbul, Turkiye 2024

### ISSUE THREAD

**Issue by halil-bugol** [cncf/kubernetes-community-days#501] opened 2023-06-19 06:00 UTC
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: YTU Davutpasa
* [x] Event Date and Time: May 15 & 16
* [x] Expected Number of Attendees: 400
* [x] Event cost per ticket, and if you will have early bird pricing or not
       Standart: 15,50 USD
* [x] Goal is to evolve into a KubeDay

#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person with workshops

#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the financial officer:
* [X] Organizer 1: Halil BUGÖL, Kubezy, Co-Founder, [halil@kubezy.com](mailto:halil@kubezy.com), CNCF Slack: Halil (Financial Officer)
* [X] Organizer 2: Emin ALEMDAR, Spacelift, Solutions Architect, [emnalmdr@gmail.com](mailto:emnalmdr@gmail.com), CNCF Slack: Emin Alemdar (CFP Admin)
* [X] Organizer 3: Batuhan APAYDIN, Trendyol, Container Dude, [batuhan.apaydin@trendyol.com](mailto:batuhan.apaydin@trendyol.com), CNCF Slack: developer-guy
* [X] Organizer 4: Ali Ok, RedHat, Principal Software Engineer, [ali.ok@redhat.com](mailto:ali.ok@redhat.com), CNCF Slack: Ali Ok
* [X] Organizer 5: Alp Kahvecioglu, Sufle, Cloud & Platform Engineer, [aakahvecioglu@gmail.com](mailto:aakahvecioglu@gmail.com), CNCF Slack: Alp Kahvecioglu
* [X] Organizer 6: Koray Oksay, Kubermatic, Site Reliability Engineer, [koray@kubermatic.com](mailto:koray@kubermatic.com), CNCF Slack: Koray Oksay
* [X] Organizer 7: Stephane Yasar, EquoSystem, Founder, [s.y@equosys.com](mailto:s.y@equosys.com), CNCF Slack: Stephane-Yasar (Financial Officer)

### Terms

* [X] No other Kubernetes Community Day event in same major city (check with past organizers)
* [X] Minimum of 3 organizers from 3 different organizations
* [X] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [X] Each organizer lives in or just outside of the KCD location
* [X] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [X] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [X] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [X] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [X] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [X] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [X] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [X] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [X] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [X] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Kubezy
İsNet
RedHat
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [X] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [X] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: istanbul-organizers@kubernetescommunitydays.org
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by halil-bugol** [comment] 2023-06-19 06:02
@developer-guy @eminalemdar

**Comment by AudMonte01** [comment] 2023-07-03 18:32
Let's set up a kick-off call for this 2024 event: https://calendly.com/audmonte/kcd-onboarding-kickoff-call

**Comment by halil-bugol** [comment] 2023-07-06 08:31
Meeting date and time has been selected. @AudMonte01

**Comment by money8203** [comment] 2023-07-11 12:48
@halil-bugol I'm up if you need any help in organizing the event!

**Comment by halil-bugol** [comment] 2023-07-12 07:22
> @halil-bugol I'm up if you need any help in organizing the event!

@money8203 As KCD activities focus on local communities.
It is organized with the organizers in the country where it will be held. For this reason, it may not be KCD, but you can follow and support our other CNCG activities in Turkey from this link https://community.cncf.io/istanbul/.

**Comment by money8203** [comment] 2023-07-12 07:37
> > @halil-bugol I'm up if you need any help in organizing the event!
> 
> @money8203 As KCD activities focus on local communities.
> It is organized with the organizers in the country where it will be held. For this reason, it may not be KCD, but you can follow and support our other CNCG activities in Turkey from this link https://community.cncf.io/istanbul/.

Yupp, I'm aware of that. Just offering virtual support, if needed in any possible way.

**Comment by halil-bugol** [comment] 2023-07-18 17:20
Kickoff meeting was held.

**Comment by AudMonte01** [comment] 2023-10-10 14:20
OCTOBER 10 UPDATE

* Team is possibly onboarding one more organizer
* Audra shared sponsor prospectus with Halil
* [ ] Halil to bring logo options to team and get back to Audra to make the LF Creative request

**Comment by halil-bugol** [comment] 2023-10-10 16:15
![image](https://github.com/cncf/kubernetes-community-days/assets/60687576/51ca6c19-d2f2-453f-933f-d8a65bf379c2)

This is our logo choice. Can we make blue colors red?

**Comment by AudMonte01** [comment] 2023-12-18 15:19
DECEMBER 18 MEETING NOTES

Website
* [ ] Team to publish Bevy page and Audra to add to drop-down list

Content
* Sessionize - Audra provided code via email on Nov 27
* Liz Rice has confirmed her speaking at the event
* Not many submissions due to end of year / holidays

New logo
* Audra shared in main KCD organizer channel
* Ali Ok is the logo person
* [ ] Audra to provide SVG file and Ali Ok will send final logo for approval to kcd@cncf.io

Sponsorships
* Quiet due to end of the year and holidays. Expecting more traction in the new year.

**Comment by AudMonte01** [comment] 2024-02-26 19:53
FEBRUARY 26 CNCF SYNC

Venue
* Waiting for final signature, but no worries on the venue not coming through (university)
* They also have a back-up venue as well (concert salon)

Ticketing
* Komunity website
* Audra gave list of registration questions
* Ticket sales will open once the contract is signed on the venue

Sponsorships
* 3 platinum and 1 Gold (waiting for contracts and payments to announce names)
-- Will announce some sponsors the beginning of March
* Other companies under discussion

Content
* Speaker acceptances have gone out, and waiting 1-2 weeks to announce the entire schedule (by end of March at the latest)
* 7 back-up speakers
* Announcing speakers socially as they confirm

**Comment by AudMonte01** [comment] 2024-03-25 18:53
March 25 CNCF Sync

Marketing
* Venue: Backup venue is a concert hall, and public transportation is good (financial center)
* Agenda: Due to release first week of April
* Tickets: Goal to release agenda and tickets at the same time

Bevy
* [ ] Team to change to "meetup' event type and leave in draft mode

Sponsorships
* 5 sponsors

**Comment by AudMonte01** [comment] 2024-04-22 17:52
APRIL 27 SYNC

* Venue: University will allow for free tickets to students
* Agenda: Release agenda and ticket sales
* Ticket sales: 14 so far

Content
* Had to replace one speaker with Ali (a lady backed out 
* 6 out of 20 (30%)

Marketing
* Reaching out to sister neighbors
* Ali will post in #sociamedia channel
* [ ] Audra to add announcement of Agenda to KubeWeekly Newsletter
* Team to explore other mediums for blog posts

Sponsorships
* 5 sponsors + 2-3 more pending
* Announcements in the beginning of May

Any other insights on KCDs in general

**Comment by AudMonte01** [comment] 2024-05-10 17:43
FINAL CNCF SYNC AHEAD OF EVENT

Tickets - 320+ and sponsors have yet to register
-- common in Turkey for people to buy last-minute
Sponsorships - AWS + another sponsor has come in
-- 15-minute slots on stage
-- Booth for swag and attendee 

Last-minute logistics
* Speaker dinner logistics
* 2-3 speakers have canceled, and already 

Emcee's
* Emin and Koray will be main
* Emin to kick-off off event with housekeeping, and working on housekeeping slides

Action
* [ ]  Audra to schedule retrospective last week of May or first week of June

**Comment by AudMonte01** [comment] 2024-05-31 18:11
MAY 31 RETROSPECTIVE WITH CNCF

Positive feedback
* Content had great feedback
-- mostly English presentations, even from Turkish speakers
-- this is due to the international audience (even local audience are expats)
* No hiccups with A/V or the venue
* The venue was well-received
* Transitions between talks were smooth

Lesson's learned
* Sponsors said there were too many students (at University), but it was only 4%
-- Perhaps have a Cloud Native novice track
* Location was intertwined with student classes, so student traffic affected
* Would be good to add the language of the talk in the session description
* Possibly longer transition times in-between the talks (10 minutes)
-- this can be done by having one less talk per day

Analytics
* Number of registrations (547) versus number of check-ins
* Total number of paid sponsors was 8, and about 5 media and community partners
-- $15k profit will be used for next year's KCD
* Total number of speakers was 21, and a total 6 women speakers (29%)

Post-event marketing
* [ ] Team will discuss who to assign Credly badges to and get back to Audra via Slack
* [ ] Ali will share completed transparency report with Audra
* Team is considering a Blog Post for cncf.io/blog and will send to pr@cncf.io if they decide to write it
* No video recordings of sessions but next year they might record keynotes and lightning talks

**Comment by AudMonte01** [comment] 2024-07-02 17:14
Hi folks @halil-bugol and @aliok - any updates on the Credly badges and if you want to use this perk from CNCF in terms if distributing these for you to speakers or volunteers or a combination of both (Contributor)?

**Comment by AudMonte01** [comment] 2024-08-05 13:43
Hello @halil-bugol - please let me know if the team is still keen on distributing Credly badges for speakers or volunteers, otherwise I will be closing this issue as complete.

**Comment by AudMonte01** [comment] 2024-08-05 21:15
Please use [this form to submit](https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform), and include the design of the badge

**Comment by AudMonte01** [comment] 2024-08-28 19:42
Credly badges were issued on August 19. This issue is now closed.

**Closed by AudMonte01** 2024-08-28 19:42 UTC
Labels: complete, EU KCD, APAC KCD
