### ISSUE TITLE
Houston K8S Days

### ISSUE THREAD

**Issue by dankirkpatrick** [cncf/kubernetes-community-days#204] opened 2019-10-22 10:33 UTC
If you do not have your team assembled, please describe the location you're interested in organizing an event, proposed dates, and information about your availability and experience with hosting a conference. If you have additional organizers and volunteers, include their information here as well. Continue to update the issue when you add new organizers and sponsors until you are ready to commit to hosting, then complete the submission checklist below. 

### Organizer 1: Dan Kirkpatrick, Frisson Computing, Consultant, dan@frissoncomputing.com 

Once you have identified your 3 organizers and 3 sponsors, please complete the information below and update your issue.

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [X] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [] Method to accept payments including sponsorships and payout expenses
* [] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [X] Minimum of 3 organizers from 3 different organizations
* [] Minimum of 3 sponsors
* [X] Each organizer needs to live in or just outside of the KCD location
* [X] No other Kubernetes Community Days event in the same city
* [X] Agree to use Eventbrite for registration
* [X] Agree to use Sched for organizing the program page

**Please include all the organizers following the format specified. At a minimum, you must have 3 organizers from 3 different organizations, and 3 sponsors.**

**Comment by KTan1226** [comment] 2019-10-24 18:42
Welcome, @dankirkpatrick! Please update your issue when you have completed the checklist.

**Comment by iennae** [comment] 2019-10-30 05:29
@dankirkpatrick is this a duplicate of https://github.com/cncf/kubernetes-community-days/issues/186 ?

**Comment by eric-magnus** [comment] 2020-01-07 19:38
Hi, I'd love to be an organizer for the Houston event - Eric Magnus, Systems Engineer with Sysdig, eric.magnus@sysdig.com

**Comment by KTan1226** [comment] 2020-01-29 22:53
@dankirkpatrick Just following up- is this a duplicate of #186?

**Comment by xmulligan** [comment] 2021-03-01 18:22
@dankirkpatrick We are relaunching the KCD program, including virtual events. We would love to have one in Houston if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).

**Closed** 2022-12-20 19:02 UTC
Labels: newevent
