### ISSUE TITLE
Internal links should not open new window

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#118] opened 2019-09-15 14:25 UTC
Click `sponsors` in the text on https://kubernetescommunitydays.org/events/2020-bouvet-island/ and it opens a new tab. The menu already works correctly.

**Comment by lucperkins** [comment] 2019-09-18 05:16
The issue is that the external link script interprets relative links like `<a href="sponsors">Sponsors</a>` as external links. It's not immediately clear to me that that's avoidable but I'll think on it.

**Comment by dankohn** [comment] 2019-09-18 11:19
The JS I recommended is brain dead. It's looking for a `/` at the beginning to signal internal, which doesn't capture our relative URL usage. Please try this approach instead: https://stackoverflow.com/a/33333648/1935918

**Comment by lucperkins** [comment] 2019-09-30 19:37
Resolved by 96a31b6f1824f08696e8cca4928e79189e9aa267

**Closed by lucperkins** 2019-09-30 19:37 UTC
Labels: bug
