### ISSUE TITLE
KCD Austria 2023 (September 26-28)

### ISSUE THREAD

**Issue by AloisReitbauer** [cncf/kubernetes-community-days#467] opened 2023-02-25 10:13 UTC
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: [Cineplexx Wienerberg](https://www.cineplexx.at/center/cineplexx-wienerberg/)
* [x] Event Date and Time:  Sept 26 - 28 2023 (2 days and 2 tracks)
* [x] Expected Number of Attendees: 300 (including 50 speakers and staff)
* [ ] Event cost per ticket, and if you will have early bird pricing or not
#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person
#### Organizers Details (identify who will be the CFP admin, as well as the financial officer)
* Erik Auer, WhizUs GmbH, CEO, [erik.auer@whizus.com](mailto:erik.auer@whizus.com), Erik Auer
* David Hirsch, Dynatrace, OSPO Program Manager, [David.hirsch@dynatrace.com](mailto:David.hirsch@dynatrace.com), David Hirsch
* David Leitner, SQUER Solutions GmbH Co-Founder, [david@squer.io](mailto:david@squer.io), David Leitner
* Daniel Drack, FullStackS GmbH, Senior DevOps/SRE Engineer, [daniel@drackthor.me](mailto:daniel@drackthor.me), Daniel Drack
* Andi (Andreas) Grabner, DevRel for CNCF Keptn, CNCF Ambassador, andreas.grabner@dynatrace.com, Andi (Andreas) Grabner
* Johannes Grumböck, Senior Cloud Platform Architect, Red Bull Media House, johannes@grumboeck.net, Johannes Grumböck
* Thomas Schuetz, Cloud Engineering Team Lead & Trainer, WhizUsWhizUs, thomas.schuetz@t-sc.eu, Thomas Schuetz

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [ ] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [ ] Provided CNCF access to all event social handles

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: [organizers-austria@kubernetescommunitydays.org](mailto:organizers-austria@kubernetescommunitydays.org)
* [x] Region created in Bevy
* [ ] Added to Bevy header
* [x] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by entlein** [comment] 2023-02-26 17:09
`+1`

**Comment by denisgolius** [comment] 2023-02-27 05:57
+1

**Comment by grabnerandi** [comment] 2023-02-27 09:29
+1

**Comment by websi96** [comment] 2023-02-27 19:58
+1

**Comment by DavidPHirsch** [comment] 2023-03-30 14:21
@AloisReitbauer the "8" in 28 is missing in the dates

**Comment by websi96** [comment] 2023-04-02 00:23
@entlein something to consider for aocc? (:

**Comment by entlein** [comment] 2023-04-02 06:55
> @entlein something to consider for aocc? (:

Yup, if there is something that is specifically suited for Unis to contribute, please the organizers get in touch with me (I’m with TUW) . 
(I ve confirmed now that I’ll be in Vienna on the date )

**Comment by DavidPHirsch** [comment] 2023-04-17 10:36
@AloisReitbauer could you set all the items in "Terms" to done and add the following as organizers:
- Erik Auer, WhizUs GmbH, CEO, [erik.auer@whizus.com](mailto:erik.auer@whizus.com), Erik Auer
- David Hirsch, Dynatrace, OSPO Program Manager, [David.hirsch@dynatrace.com](mailto:David.hirsch@dynatrace.com), David Hirsch
- David Leitner, SQUER Solutions GmbH Co-Founder, [david@squer.io](mailto:david@squer.io), David Leitner

**Comment by AudMonte01** [comment] 2023-05-09 17:49
MAY 9 MEETING NOTES

Organizers
* WhizUs is a CNCF member
* David Hirsch is an ambassador
* To-Do: Add Daniel Drack as an organizer to this GitHub issue

Venue
* Two main options (1 is a local university)

Funding
* Applied for 50% funding via city of Vienna (food, logistics, promotion)
* Sponsor prospectus created in the next week or so

CFP
* Might launch it at the end of May and keep it open for 8 weeks (Closes end of July)

To-Dos
* David to send logo for review
* Audra to create Bevy chapter
* Audra to add Daniel and Henrik Rexed as CFP admins

**Comment by DavidPHirsch** [comment] 2023-06-05 10:05
@AudMonte01 could you please add him to the organizers and create the shared email
- Daniel Drack, FullStackS GmbH, Senior DevOps/SRE Engineer, daniel@drackthor.me, Daniel Drack

**Comment by DavidPHirsch** [comment] 2023-06-15 08:28
@AudMonte01 sadly, for the moment we do not

**Comment by k8tgreenley** [comment] 2023-06-20 17:36
Email alias has been created: organizers-austria@kubernetescommunitydays.org

**Comment by AudMonte01** [comment] 2023-06-27 15:30
JUNE 27 MEETING UPDATES

Content
* 32 submissions so far and end of July is the deadline
* 3 keynotes speakers confirmed and 1 pending

Tickets have been LIVE last week

Sponsors
* RedHat, AWS, Dynatrace, A1, RedBull, WhizUs (90% confirmed)
* Possible funding from the city of Vienna
* Food can still be cut

Marketing
* Focusing on diversity scholarship for 5-10 tickets (including students)

Action item
* [ ] David to send Audra language ahead of posting on LinkedIn
* [ ] Audra to look into templates for student and diversity scholarship surveys
* [ ] Audra to email certification vouchers for a raffle

**Comment by AudMonte01** [comment] 2023-09-11 18:18
SEPTEMBER 11 MEETING NOTES 

Sponsorships
* At a breakeven, and will come ahead provided signed sponsors all pay

Content
* Keynote speaker swap due to last-minute cancelation
* End of day will be a game-style giveaway

Collaboration
* Daniel to add Audra to weekly syncs going forward
* Daniel to use Bevy for speaker communications

**Comment by AudMonte01** [comment] 2023-11-02 16:55
RETROSPECTIVE MEETING NOTES (NOVEMBER 2)

Pros of the event
* Overall the experience was great and they are eager for next year
* 104 responses in the survey
-- had QR code at the end of the last presentation + closing email
* Logistics ran nearly seamlessly
* Cinema as a venue was well received
* General feedback: LinkedIn was used mostly for social

Cons / lessons learned
* With a collective of 10 organizers, there needs to be 1 or 2 lead organizers, as well as clarifying roles
* Better reviewing process from ratings and the same questions in mind
-- review ahead of closing, and be transparent with attendees about
-- don't review during holidays
* Set submission standards
* Some folks thoughts the breaks were too abundant
* Too many tools in the end and switching made it hard to track

CNCF feedback
* Templates for guidance, but not guardrails for social media

Data
* Total registered versus total checked in (300 w/ 293 attended, so 98%)
* Total speakers with non-male speaker percentage
-- 35 speakers of which 6 were non-male (17% diversity of gender)
-- all 3 were non-male
-- 123 applicants, 14 woman, 1 non-binary
* Total sponsors with insight into profit or loss (13 paid + 6 community)
-- profit of 5k without the city of Vienna. With help 25-30k profit
-- will use extra funds for next year's KCD and help local meetups through the association 
* Transparency report template has been shared (waiting on some data and photos)
* Final marketing to prolong content (videos, blog post, etc)
* [ ] Audra to duplicate the YouTube channel KCD Austria playlist on CNCF channel
* [ ] Team will be marketing videos with reels, and social posts
* [ ] Daniel will draft a blog post for CNCF blog
* Might be wanting 

KCD 2024 will be Sept/Oct
* Will collaborate with Munich & Zurich for marketing

**Comment by AudMonte01** [comment] 2024-02-07 17:26
[Transparency report published last week](https://www.cncf.io/reports/kcd-austria-2023/)
Blog due to post this week via cncf.io/blog

**Closed by AudMonte01** 2024-02-07 17:26 UTC
Labels: complete
