### ISSUE TITLE
KCD UK 2023 (October)

### ISSUE THREAD

**Issue by yankcrime** [cncf/kubernetes-community-days#462] opened 2023-01-26 12:26 UTC
# KCD Organizer Checklist

### Event Details
Event Location: CodeNode, London, UK
Event Date and Time: October 17, 2023
Expected Number of Attendees: ~ 350
Event cost per ticket, and if you will have early bird pricing or not: TBC, will have early bird pricing

#### Event type:
In person

### Organizer 1:

Matt Jarvis, Snyk, Director of Developer Relations, [matt@mattjarvis.org.uk](mailto:matt@mattjarvis.org.uk), Matt Jarvis

### Organizer 2:

Carla Gaggini, Container Solutions, Head of Events, [carla.gaggini@container-solutions.com](mailto:carla.gaggini@container-solutions.com), Carla Gaggini

### Organizer 3:

Nick Jones, EscherCloudAI, Head of Cloud Native, [nick@dischord.org](mailto:nick@dischord.org), yankcrime

### Organizer 4:

Adrian Mouat, Chainguard, [adrian.mouat@gmail.com](mailto:adrian.mouat@gmail.com), mouat

### Organizer 5:

Lewis Denham-Parry, Chainguard, Head of Training, [lewis@cloudnativewales.io](mailto:lewis@cloudnativewales.io), denhamparry

### Organizer 6:

Chris Kranz, [chris@kranz.com](mailto:chris@kranz.com) , chris kranz

### Organizer 7:

Josh Michielsen, Weaveworks, Technical Lead, [j@mickey.dev](mailto:j@mickey.dev), jmickey

### Organizer 8:

Danny Abukalam, SoftIron, Director, Product Engineering, [danny@abukalam.com](mailto:danny@abukalam.com), dabukalam

### Organizer 9:

Paula Kennedy, Syntasso, Chief Operating Officer, [paula.louise.kennedy@gmail.com](mailto:paula.louise.kennedy@gmail.com), Paula Kennedy

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [ ] Provided CNCF access to all event social handles

### Getting started checklist for CNCF:
* [ ] Organizer email alias has been created
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in SMapply
* [x] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [x] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [x] Send CNCF event analytics
* [x] Schedule post mortem meeting
* [x] Send CNCF videos to be uploaded to YouTube
* [x] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [x] Removed from Bevy header
* [x] CFP deactivated
* [x] Upload videos to YouTube

**Comment by AudMonte01** [comment] 2023-01-30 14:34
Excellent! @k8tgreenley - can you please create an email alias for the above organizers?

**Comment by k8tgreenley** [comment] 2023-02-01 19:15
This has been updated

**Comment by AudMonte01** [comment] 2023-05-19 18:27
MAY 18 MEETING NOTES

Program
* Same venue
* Tues/Wed event with Speaker event on Monday night (Wednesday felt as busy as day 1)
-- travel on Monday seems to be good and easy
-- drop-out day on Friday is high because folks think of it was a weekend
* Same caterer with a different menu
* Same Bevy and SM Apply usage
* Tickets went on sale today
* Reach out for speakers happening now
-- 30 submissions to the CFP so far and it doesn't close until July 2

To-Dos
* Audra sent voucher codes

**Comment by ckranz** [comment] 2023-05-23 17:41
@k8tgreenley my email address has been updated (issue here updated), can you please update the email alias to remove my old email and add my new one please?

- chris.kranz@sysdig.com
+ chris@kranz.com

Many thanks!

**Comment by k8tgreenley** [comment] 2023-05-23 17:51
@ckranz this is now updated to reflect your email change

**Comment by amouat** [comment] 2023-06-20 15:05
@k8tgreenley could someone check my e-mail address? I don't get any messages. It should be adrian.mouat@gmail.com

**Comment by AudMonte01** [comment] 2023-06-27 21:00
JUNE 27 CHECK-IN NOTES

Content
* The CfP will close on 2nd July at 23:59 BST and we will make notifications by 31st July 2023.
* 92 applications so far
* About 32 slots to fill including keynotes
* Keynotes: Inviting Liz Rice and Anais to keynote

Tickets
* Using Ti.to again

Sponsorships
* Target 3 platinum + 12 gold
* 2 platinum, 4 gold signed up
-- need 1 more platinum and 8 more gold but have many many leads and interest

**Comment by AudMonte01** [comment] 2023-07-25 14:53
JULY 25

Content
* Matt Jarvis will do first pass at selection
* Everyone is finishing reviewing
* Diversity is looking good
* Male speakers will be UK-based
* 8 keynotes, 23 breakouts, and 1 retrospective panel at the end of the event
-- goal 50% women for keynotes
-- goal 43% women in sessions
* Sending CFP notifications on Monday the 31st
* Agenda due to be announced August 29 (over 6 weeks of marketing agenda)

Sponsors
* 7 confirmed out of 20

Action items
* [ ] Paula to send Audra prospectus to add to the GitHub repo (linked from KCD home page)
* [ ] Audra to add early bird tickets to KubeWeekly newsletter for this week

**Comment by AudMonte01** [comment] 2023-08-15 14:10
AUGUST 15 UPDATE

* 24 tickets sold
* 11 sponsors confirmed out of 20
* Agenda should be announced 29th August (still waiting for a few speakers to confirm)

**Comment by AudMonte01** [comment] 2023-10-02 20:35
OCTOBER 2 NOTES

Tickets
* almost to 50% of goal

Sponsors
* 1 platinum, 13 gold and 1 silver
* 1 event sponsor available

**Comment by AudMonte01** [comment] 2023-10-13 17:53
OCTOBER 13 MEETING NOTES

TICKETS
* Nearly sold out (capped at 260 based on 95% turnout last year)\
-- 50 sponsors and 37 speakers
* Catering for 200-240 (breakfast, breaks, and lunch)
* 270 is comfortable in the main stage room

SPONSORS
* All but 2 have paid, but those 2 have been in communication
* 1 platinum, 13 gold, and 1 silver
* Already past breakeven point
* Live captioning, evening pizza + drinks for drinks, covering some t & l for speakers, speaker gifts
* Sponsor raffle with a passport and stamps

CONTENT
* 1 track of workshops
* Job drop-in clinics with the extra room
-- like how to improve your LinkedIn profile
-- interview tips
* Open mic for the last session

**Comment by AudMonte01** [comment] 2023-11-02 20:03
YouTube videos have been uploaded by team. I have copied the playlist over to CNCF YouTube channel.
* [ ] retrospective meeting needs to be held.

**Comment by AudMonte01** [comment] 2023-11-09 20:01
RETROSPECTIVE MEETING

Pros
* Sold out show
* Danny and Nick are great as fiscal sponsors that have the business-savvy experience
* Use Ti.to for reg system and can see really good analytics, as well as printed QR codes on stickers for sponsor scanning on-site
* Super raffle worked (lego, O'Reilly books, training vouchers). Folks stuck around to collect prizes
* Team work was well
* 1 track of workshops was better than 2 they had last year
* Final panel was well-received. Included 2 keynotes from the morning
* Day-of signups for lightning talks
* "the best conference they've ever been to"
* diverse lineup in gender and age, but found a balance of quality and supporting local community

Cons
* Lanyards ran out
*  1 sponsor still owes
* Closing keynote speaker didn't show, BUT a panel pulled together about the future of open source
* Hard to find a reliable vendor for sponsors
* Don't be a sponsor rep and organizer at the same time
* Workshop after keynotes (not during)

Ideas for 2024
* Pitch/demo pavilion for sponsors next year
* 3 volunteers + 7 organizers on-site, but could have had more
* stick to UK and change location, or divide up and do city-specific
* 300 is sweet spot

Stats
* 260 and 15% drop-out rate
* 35% diversity (non-male)
* 10k profit and will donate to a non-profit

**Comment by AudMonte01** [comment] 2023-11-09 20:05
Action Items
* [ ] Audra shared transparency report template with Paula
* [ ] Does the team want to write a blog post for CNCF.io?
* [ ] does the team want to have 1 special Credly badge, and for whom?

**Comment by AudMonte01** [comment] 2024-01-09 21:56
Credly Badges issue to organizers.

Volunteers badges to come!

**Comment by AudMonte01** [comment] 2024-02-07 17:24
Closing this issue, as I have not heard back about additional Credly badges, and a blog post.

**Closed by AudMonte01** 2024-02-07 17:24 UTC
Labels: complete
